---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-dev
  labels:
    name: chaos-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-dev
  labels:
    name: chaos-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: chaos-dev