apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: chaos
spec:
  appinfo:
    appns: ''
    applabel: 'app=nginx'
    appkind: 'deployment'
  # It can be true/false
  annotationCheck: 'true'
  # It can be active/stop
  engineState: 'active'
  #ex. values: ns1:name=percona,ns2:run=nginx
  auxiliaryAppInfo: ''
  chaosServiceAccount: chaos-dev
  monitoring: true
  # It can be delete/retain
  jobCleanUpPolicy: 'retain'
  experiments:
    - name:  container-kill
      spec:
        components:
          env:
            - name: TARGET_CONTAINER
              value: doesnt-exist
            - name: DEFAULT_GATHERING
              value: "explicit"
            - name: LIB_IMAGE  
              value: 'litmuschaos/go-runner:latest'               
            - name: LIB
              value: 'litmus'
            - name: CHAOS_INTERVAL
              value: '5'
            - name: TOTAL_CHAOS_DURATION
              value: '10'